load("//:subdir_glob.bzl", "subdir_glob")

cxx_binary(
    name = "gameoflife",
    header_namespace = "gameoflife",
    headers = subdir_glob([
        ("include", "**/*.hpp"),
    ]),
    srcs = glob([
        "src/**/*.cpp",
    ]),
    deps = [
        "//utilscpp:utilscpp",
        "//:sdl",
    ],
)
