go_binary(
    name = "runner",
    srcs = [
        "cmd/runner/main.go",
    ],
    deps = [
        "//gameoflifeServer/workers:workers",
    ],
)

go_binary(
    name = "server",
    srcs = ["cmd/server/main.go"],
    deps = [
        "//gameoflifeServer/connect:connect",
    ],
)

go_binary(
    name = "client",
    srcs = ["cmd/client/main.go"],
    deps = [
        "//gameoflifeServer/connect:connect",
    ],
)
