name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: sudo apt update && sudo apt install -yq curl openjdk-8-jre-headless python2.7 gcc libsdl2-dev libcurlpp-dev openssl1.0
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.1'
      - name: Buck build
        uses: GuilleDF/buckaroo-action@v1.0.3
        with:
          commands: buckaroo install && buck build //...
