name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependecies
        run: sudo apt update && apt install -yq curl openjdk-8-jre-headless python2.7 libicu60 libxml2 gcc
      - name: Install buck
        run: |
          curl -L https://github.com/facebook/buck/releases/download/v2019.10.17.01/buck.2019.10.17.01_all.deb -o buck.deb
          dpkg -i buck.deb
          rm buck.deb
          ln -s /usr/bin/python2.7 /usr/bin/python
      - name: Build
        run: buck build //...
