name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Buck build
        uses: GuilleDF/buckaroo-action@v1.0.3
        with:
          commands: buckaroo install && buck build //...
