name: lint
on: [push, pull_request]
jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - run: pip install cpplint
      - run: cpplint --recursive .
  golint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: Jerome1337/gofmt-action@v1.0.4
        with:
          gofmt-flags: '-l -d'
  pylint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./azure/simulationsApp
    steps:
      - uses: fylein/python-pylint-github-action@v1
        with:
          args: pip3 install -r requirements.txt && pylint ./start_orchestrator
